get:
  summary: Get a list of products
  responses:
    200:
      description: A list of products
      schema:
        type: array
        items:
          type: object
          properties:
            id:
              type: integer
              description: The product ID
            name:
              type: string
              description: The product name
            price:
              type: number
              description: The product price
